/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { BaseV1Router, BaseV1RouterInterface } from "../BaseV1Router";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
    ],
    name: "getAmountOut",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "stable",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BaseV1Router__factory {
  static readonly abi = _abi;
  static createInterface(): BaseV1RouterInterface {
    return new Interface(_abi) as BaseV1RouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BaseV1Router {
    return new Contract(address, _abi, runner) as unknown as BaseV1Router;
  }
}
